name: Orion Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
    - name: Setup node12
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Build with Maven
      run: mvn -B package --file pom.xml
